import dash
import dash_bootstrap_components as dbc
from dash import html


dash.register_page(__name__, path='/Project1')
from .Homoscroll import scroll_layout


content = html.Div([

        html.H1("Project 1: Skeletal Phenotyping of 220 Knockout Mouse Lines", className="display-5", style={'text-align':'center'}),
        html.P(
            "The data for project 1 consists of μCT and bone histomorphometry analysis of femoral and vertebral bones."
            " Phenotyping was performed on 12 week old male and female homozygous knockout mouse lines generated by"
            " the Knock Out Mouse Project (KOMP). Please select from the buttons in the above scroll bar to view datasets."
            " Lighter blue buttons connect to μCT datasets. Darker blue buttons connect to histomorphometry datasets,"
            " and the gray button directs you to a page that allows you to view data rapidly for individual genes. ",
            className="lead",
        ),
        html.Hr(className="my-2"),
        html.P(
            "Please Select the Button Below To Learn More About Our Projects"
        ),
        html.P(dbc.Button("Learn more", href="https://bonebase.lab.uconn.edu/projects-data/",color="primary"), className="lead"),



    ],  style = {'border-style': 'solid', 'border-color': 'black', 'gray': 3, 'background-color':'#d1d1d157','margin-left':-48})


def layout():
    return html.Div([ dbc.Container ([


                html.Div([

                    dbc.Row(scroll_layout()),
                    dbc.Row(html.Br()),
                    dbc.Row(content)

                     ]) ,


        ])
])