import dash
import dash_bootstrap_components as dbc
from dash import html,callback,Input,Output


dash.register_page(__name__,path='/Project2')
from .Hetscroll import scroll_layout

content= html.Div(
    [
        html.H1("Project 2: Phenotyping of 50 Heterozygous Knockout Mouse Lines", className="display-5", style={'text-align':'center'}),
        html.P(
            "We are actively generating the data for Project 2 and will update our progress monthly. Included in the data portal, thus far, "
            " is μCT analysis of femoral and vertebral bones. Histomorphometry measurements are actively being performed and we hope to report"
            " this information soon. As in Project 1, phenotyping was performed on 12 week old male and female heterozygous knockout mouse lines"
           " generated by the Knock Out Mouse Project (KOMP). Please select from the buttons in the above scroll bar to view datasets."
            " Lighter blue buttons connect to μCT datasets. Darker blue buttons connect to histomorphometry datasets,"
            " and the gray button directs you to a page that allows you to view data rapidly for individual genes. ",
            className="lead",
        ),
        html.Hr(className="my-2"),
        html.P(
            "Please Select the Button Below To Learn More About Our Projects"
        ),
        html.P(dbc.Button("Learn more", href="https://bonebase.lab.uconn.edu/projects-data/",color="primary"), className="lead"),



    ],  style = {'border-style': 'solid', 'border-color': 'black', 'gray': 3, 'background-color':'#d1d1d157','margin-left':-50},
),


def layout():
    return html.Div([ dbc.Container ([


                html.Div([
                    dbc.Row(scroll_layout()),
                    dbc.Row(html.Br()),
                    dbc.Row(content)
                 ]) ,

        ])
])